import { describe, expect, it } from 'vitest';
import { ChatRequestSchema } from './chat-request.dto';

const body = (id: string) => ({
  id,
  messages: [{ id: 'm1', role: 'user', parts: [] }],
});

describe('ChatRequestSchema', () => {
  it('accepts ids generated by the client', () => {
    expect(ChatRequestSchema.safeParse(body('aB3_x-9KqZ')).success).toBe(true);
    expect(
      ChatRequestSchema.safeParse(body('0b7f4a7e-6d1c-4c8e-9a51-1f2d3c4b5a69'))
        .success,
    ).toBe(true);
  });

  it('rejects a conversation id with path characters', () => {
    for (const id of ['../images', '..%2Fimages', 'a/b', 'a\\b', '.', '']) {
      expect(ChatRequestSchema.safeParse(body(id)).success).toBe(false);
    }
  });
});
