import Image, { type ImageProps } from "next/image";

/**
 * Images generated by the toolkit are served by our own API
 * (`/api/generations/:id/image`). They are already final JPEG/PNG files, and
 * Next's image optimizer refuses to fetch from private/local hosts (where the
 * API lives in dev and Docker), so they are rendered unoptimized.
 */
export function GeneratedImage({ alt, ...props }: Omit<ImageProps, "unoptimized">) {
  return <Image alt={alt} {...props} unoptimized />;
}
